### ISSUE TITLE
Add PIN-Protection for user account

### ISSUE THREAD

**Issue by schinken** [strichliste/server#1]
Add possibility to set user pin and access to this account needs authentication as some users want to protect their account

**Comment by schinken** [comment]
* Which hashing algo. would one use? (http://php.net/crypt with salt I guess)
* HTTPs-Only feature?

**Comment by schinken** [comment]
Found out one would use `password_hash` and `password_verify`

**Comment by schinken** [comment]
Still two options here:

* Should we protect the API endpoints /user/{userId} and /user/{userId}/transaction, requiring authentication (HTTP 401)
* Should we just provide a /user/{userId}/authenticate endpoint, where the api consumer can authenticate against with a password in JSON-Body

Disadvantage of the first method is, that automatic reporting, crons etc. can't access user details/transactions anymore - because they obviously don't know the users password.

In my opinion we should go with the second one and explicitly document that behavior and why we decided that way

**Comment by encbladexp** [comment]
I would prefer variant 3. Basic auth is ugly.

**Comment by schinken** [comment]
Or option 4:
Let the front-end do the job and just provide an authentication endpoint

**Comment by bobapple** [comment]
In my opinion it depends on the intention behind the API:
* Do users have access to that API? (Get reports, run automated transactions) If there's an API, users usually want to use it, especially in your environment 

Assuming that users actually use that API, as a I user I want:
* That nobody else can access my data (history) or run any transactions without my PIN
* Easy access. Splitting some methods with authentication and some without leads to confusion

As an administrator or maintainer I want:
* Access to everything
* To run my cronjobs without using the users credentials
* Limit access, users should not be able to run reports about every other user and therefore retrace buying behaviour of other users

Conclusion:
I would generally allow access to the API only to authenticated users, independent if it's a GET or POST request. A user can only get data about himself and only run transactions for himself. A special `Admin` user can access everything, this user is used for your cronjobs. A fully blown feature (later version?) would support groups and roles to control access. For simplicity reasons, I would prefer basic auth.

**Comment by sanderdrummer** [comment]
Why not two-factor authentication 😁.

Just kidding I think the no exceptions rule is reasonable because of kiss. 

From a frontend perspective ->
How should the user workflow be handled? 
I want to pay, I authorize by pin then I am authenticated for like 1minute do my stuff then the session is invalid again? Or do I have to store the pin in the client as a "token" and delete it after some time? 

We must not forget as soon as a user sets a password it's likely that the user will forget it 🤔. So we need some features to reset or modify the pin as well. 

Just my 2 cents 😇😇😇.

**Comment by schinken** [comment]
After discussion this with several people, i've come to the conclusion I won't implement that feature
* Strichliste is all about trust - if you don't have it, strichliste is not the right thing for you
* It has a lot of complexity to do pin protection right
* It has a lot of disadvantages for the API usage of cronjobs etc
