### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by NicoHood** [strichliste/server#22]
Is this production ready and how can I install it? How to migrate from existing installations?

**Comment by schinken** [comment]
Hi Nico,

it works, but the frontend needs a lot of design work. You can try it here http://v2.strichliste.org.
I will provice a INSTALL.md as soon as it's ready.

But here's a quick tutorial:
* Pick a release here: https://github.com/strichliste/server/releases
* Extract the tar.gz file into your /var/www/domain.tld
* Configure your apache (https://symfony.com/doc/current/setup/web_server_configuration.html#apache-with-mod-php-php-cgi)
* Or nginx (https://symfony.com/doc/current/setup/web_server_configuration.html#nginx)
* Move var/app.db.example to var/app.db (this has to be done the first time, after that, you have your own app.db)
* maybe chown the whole directory to your www-data
* done

Be aware: I might change the database layout in the coming days again (maybe add quantity to transaction, add some indexes, etc...)

**Comment by schinken** [comment]
Ah btw, a docker-file is coming soon, too. Also the install instructions contain instructions how to set up the server with different databases

**Comment by schinken** [comment]
http://www.strichliste.org/install/

**Comment by NicoHood** [comment]
How do I manually build this software? Which dependencies are required? And where are the setting files located?

**Comment by schinken** [comment]
Look at this https://github.com/strichliste/strichliste-backend/blob/master/.travis.yml#L4

That's basically it. glone, composer install, done. 
Deleting cache might be unnecessary for you.
