### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by schinken** [strichliste/server#23]

**Comment by Bouni** [comment]
Any news on this?
I would like to run strichliste in our hackerspace and a docker file would be quite nice :-)

**Comment by schinken** [comment]
Hi Bouni,

there is an open pull request for this. But I'm not quite satisfied with the solution. Do you have experience in creating such files and want to help with that?

As strichliste2 can run with multiple backends it may be cool to use something other than sqlite for docker. Maybe a linked postgres/mysql container using docker-compose.

I'm not an experienced docker user, but I know some concepts. I don't know the "best practice" - but that's always that solution I'm striving for.

Best,
schinken

**Comment by Bouni** [comment]
Hi,

unfortunately I have no more docker experience than pulling and starting docker containers.
I've tried to create a simple docker file for strichliste that solves my use case but even failed with that 😞 
I'll take a look at #26 and see if can make something out of it that works for me.
If I come up with a clean solution I'll let you know!

**Comment by CptPie** [comment]
Hey,
i worked writing a docker-compose file including a custom Dockerfile which uses the current version (1.2.3). Since it is based on the docker branch of https://github.com/stp-ip/server and i haven't forked any repository i am unable to create a pull request.

The Mentioned implementation can be found here: https://github.com/CptPie/strichliste
As said in the README it should run without any previous configuration but still needs a lot of work

**Comment by schinken** [comment]
What do you think about a separate repository strichliste-docker unter strichliste organization.
I think its better then packing everything in the normal project repo, i guess?

**Comment by schinken** [comment]
Found the import feature in github ;) 
https://github.com/strichliste/strichliste-docker

(currently processing)

**Comment by CptPie** [comment]
> I think its better then packing everything in the normal project repo, i guess?
yeah i think that would be a better idea :)

**Comment by schinken** [comment]
I would close that issue here and refer to https://github.com/strichliste/strichliste-docker
But this also needs some more work! Please see the issues there
