### ISSUE TITLE
Refactor user active to isActive to be consistent

### ISSUE THREAD

**Issue by sanderdrummer** [strichliste/server#25]

**Comment by schinken** [comment]
You mean that URL parameter?

**Comment by schinken** [comment]
Aaah fuck. Sorry. I mixed up my stuff. I rename it to isStale, because active means something else. Wait a sec.

**Comment by schinken** [comment]
https://github.com/strichliste/server/commit/5405d5ddcdabf1eaba69ccf862f6949baaa93c86

Check this commit. The parameter is now `isStale` at the user response. You can filter by using ?stale=true/false. If you don't use that parameter, you get all of the users back
