### ISSUE TITLE
Improve responses for /api and / 

### ISSUE THREAD

**Issue by kmille** [strichliste/server#35]
/api/ returns a 500
/ returns a 'FrontEnd not found'

Can you please fix this

**Comment by schinken** [comment]
Ha, looks like a symfony bug:
* https://github.com/symfony/symfony/pull/27519
* https://github.com/symfony/symfony/issues/25844

**Comment by schinken** [comment]
https://demo.strichliste.org/api/ now returns 404. symfony.lock kept back my symfony 4.2 update recently... meh.
