### ISSUE TITLE
Skript for migrating database from strichliste v1

### ISSUE THREAD

**Issue by kmille** [strichliste/server#36]
Hey,
do you have a script for migrating the database from strichliste1 to strichliste2?
The schema changed a lot.

Greetings from CCCDA

**Comment by schinken** [comment]
Oh sorry, missed it in the commands section. Will add these asap. 
Look at the install instructions: https://www.strichliste.org/install/

**Comment by schinken** [comment]
Done! Added it to https://github.com/strichliste/server/blob/master/docs/Commands.md
