### ISSUE TITLE
Change custom dispense steps

### ISSUE THREAD

**Issue by kmille** [strichliste/server#37]
Hey,
maybe I'm too old for the new fancy web framworks. I try to change the custom steps for the dispenses in config/services.yaml but it does not get applied. It's not getting cached as far as I can see (we use you're nginx config)

config/services.yaml

            dispense:
                enabled: true
                custom: true
                steps:
                    - 20
                    - 100
                    - 200
                    - 500
                    - 112

After restarting  nginx we still get the old values ...

```
kmille@homebox server master % curl  -s 'http://localhost:8080/api/settings' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:8080/' -H 'Connection: keep-alive' --compressed | jq '.settings.payment.dispense'
{
  "enabled": true,
  "custom": true,
  "steps": [
    50,
    100,
    200,
    500,
    1000
  ]
}
```

There was no access to the service file
```
root@prepaid:/opt/strichliste2_backend/config# strace -e file -o trace $(pgrep php-fpm | xargs -i echo -p {} | xargs)
strace: Process 431 attached
strace: Process 457 attached
strace: Process 458 attached
strace: Process 570 attached
^Cstrace: Process 431 detached
strace: Process 457 detached
strace: Process 458 detached
strace: Process 570 detached
root@prepaid:/opt/strichliste2_backend/config# cat trace | grep service
root@prepaid:/opt/strichliste2_backend/config# ls
bundles.php  packages  routes  routes.yaml  services.yaml  trace
```

How can I fix it...?

**Comment by kmille** [comment]
fixed it :/
bin/console cache:clear

**Comment by schinken** [comment]
I will add this to my documentation. Sorry for that to be unclear. 
It's interesting to see what's missing in docs/etc, because if you're inside the "bubble" you'd think "of course if have to clear cache" and don't think about it anymore that others might not have known this.

**Comment by kmille** [comment]
I was looking for the settings in the front end in the first place. There was a frontend.js in StrichlisteV1.

**Comment by schinken** [comment]
I was also thinking about splitting settings. Some are relevant for frontend/some for backend. But I actually don't know if thats more confusing than helping. 

I would change that if there were more clients than one (ncurses, ... etc)
