### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by mweinelt** [strichliste/server#38]
Users coming from LDAP would be a nice addition. Also allowing a different credit limit for accounts coming from LDAP vs. guest accounts would be awesome.

**Comment by schinken** [comment]
Woah nice... there is a new feature in github to transfer issues Oo

**Comment by schinken** [comment]
Ok seems it's broken :D

**Comment by mweinelt** [comment]
Naaah, still copyiiiiiing :D

**Comment by schinken** [comment]
@mweinelt Check out the commit https://github.com/strichliste/server/commit/5026e09b4ad925a107caaa6e241aed8fa760514a

It's not yet packaged into a release - but you can try from master. Works with my LDAP ;)

**Comment by schinken** [comment]
Look at https://github.com/strichliste/server/commit/5026e09b4ad925a107caaa6e241aed8fa760514a

**Comment by mweinelt** [comment]
Maybe also allow for a custom filter.

**Comment by schinken** [comment]
Is `query | LDAP filter query (default: ($userField=*))` not sufficient? Do I miss something here?

**Comment by mweinelt** [comment]
*derp*

forget I ever said anything.

**Comment by schinken** [comment]
no problem :)

**Comment by schinken** [comment]
Does it work so far? :)

**Comment by mweinelt** [comment]
I kindly ask @kmille to assist me in that matter, when he has the time.

**Comment by kmille** [comment]
Sure @mweinelt
