### ISSUE TITLE
Split invoice - Failed to create Transaction

### ISSUE THREAD

**Issue by CptPie** [strichliste/server#43]
Version: 1.2.3
Using: strichliste-docker repository
Hostsystem: Manjaro 18.0.2, Kernel 4.19.13

It seems that the payment between users fails undeterministically if there are more than 2 users affected.

Steps to reproduce:
- Use the split invoice feature
- enter a random amount
- enter a recipient 
- enter atleast 2 participants
- submit the form

I don't know why exactly it fails, it seems to be independend from the balance of the individual users and the amount provided.
I only could reproduce the issue with more than 2 participants - for one participant it seems to work fine.

**Comment by schinken** [comment]
arghs... maybe sqlite does not support transactions. try to reproduce that.... :/

**Comment by schinken** [comment]
Jip, damnit. Sqlite does not support PESSIMSTIC_WRITE as a lock feature for transactions.

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L1360

Does not overload that:
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/SqlitePlatform.php

I guess I should update the docs and recommend/make mysql as a default

**Comment by schinken** [comment]
I've updated the install instructions: https://www.strichliste.org/install/
Can you update your docker container maybe to use a good DB? :D

**Comment by CptPie** [comment]
I will look into that but i am not sure when i get around doing so :)
